backend: 
  name: git-gateway

media_folder: "src/images"

collections:
  - name: "content"
    label: "Content"
    files:
      - label: "Biography"
        name: "biography"
        file: "src/content/biography.md"
        fields:
          - {label: "Text", name: "body", widget: "markdown"}

      - label: "Repertoire"
        name: "repertoire"
        file: "src/content/repertoire.md"
        fields: 
          - {label: "Text", name: "body", widget: "markdown"}

      - label: "Videos"
        name: "videos"
        file: "src/content/video-urls.json"
        format: "json"
        fields: 
          - label: "Videos"
            name: "videos"
            widget: "list"
            fields: 
              - {label: "Video Title", name: "title", widget: "string"}
              - {label: "Video Url", name: "url", widget: "string"}

      - label: "Photos"
        name: "photos"
        file: "src/content/photos.json"
        format: "json"
        fields:
          - label: "Photos"
            name: "photos"
            widget: "list"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Description"
                name: "description"
                widget: "string"
              - label: "Press Photo"
                name: "press"
                widget: "boolean"
                default: false