backend: 
  name: git-gateway

media_folder: "src/images"

collections:
  - name: "biography"
    label: "Biography"
    file: "src/content/biography.yml"
    fields:
      - {label: "Text", name: "body", widget: "markdown"}