backend: 
  name: git-gateway

media_folder: "src/images"

collections:
  - name: "content"
    label: "Content"
    files:
      - label: "Biography"
        name: "biography"
        file: "src/content/biography.yml"
        fields:
          - {label: "Text", name: "body", widget: "markdown"}